Pages for add users and orders
axlrommel/nextjs-sample-proj pull request #1
Opened 2024-09-18 01:43 UTC by crisan52

Implementation of users and orders pages.
This PR includes Luxon lib to manage Date and Times.
TypeScript was used to follow a standard over Object Structures.
On this PR a new component to view detail orders was included to reuse in different pages & call from user detail, orders, and orders detail pages.

2024-09-18 15:15 UTC, axlrommel requested changes
Overall looks good. One question though. How is the orders page useful? You are just listing the orders, which is fine but from a user standpoint, how can they leverage that information. I want you think what changes would you make to that page to make it useful to a user. Or put yourself in the shoes of the user: What would I want to see there?

2024-09-18 22:02 UTC, crisan52 commented
> Overall looks good. One question though. How is the orders page useful? You are just listing the orders, which is fine but from a user standpoint, how can they leverage that information. I want you think what changes would you make to that page to make it useful to a user. Or put yourself in the shoes of the user: What would I want to see there?

@axlrommel Thanks for the feedback on the code. Yeah, I understand exactly what you explain. 

In my first version, I only follow the instructions to give functionality adding pages to users and orders. But I agree with you that isn't what the user spect. I think the initial version could be great for an admin user who needs to manage all the information entered into the system by the final users. 

So following the requirements I added new changes to start navigating the application hierarchically, first listing a client directory, in the next level the orders created by a specific user, and choosing a particular order you can view the details of the products of an order. 

What's next? I would implement the authentication module, to visualize only the logged-in user information. Also with the Auth, we can manage roles to grant admin permission and implement new pages to view all the system information.

2024-09-18 22:13 UTC, axlrommel commented
Christian,

That’s great, no need to go any further. Let’s find sometime to talk this
week
Well done
Rommel

On Wed, Sep 18, 2024 at 17:02 Christian Salinas ***@***.***>
wrote:

> Overall looks good. One question though. How is the orders page useful?
> You are just listing the orders, which is fine but from a user standpoint,
> how can they leverage that information. I want you think what changes would
> you make to that page to make it useful to a user. Or put yourself in the
> shoes of the user: What would I want to see there?
>
> @axlrommel <https://github.com/axlrommel> Thanks for the feedback on the
> code. Yeah, I understand exactly what you explain.
>
> In my first version, I only follow the instructions to give functionality
> adding pages to users and orders. But I agree with you that isn't what the
> user spect. I think the initial version could be great for an admin user
> who needs to manage all the information entered into the system by the
> final users.
>
> So following the requirements I added new changes to start navigating the
> application hierarchically, first listing a client directory, in the next
> level the orders created by a specific user, and choosing a particular
> order you can view the details of the products of an order.
>
> What's next? I would implement the authentication module, to visualize
> only the logged-in user information. Also with the Auth, we can manage
> roles to grant admin permission and implement new pages to view all the
> system information.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/axlrommel/nextjs-sample-proj/pull/1#issuecomment-2359481501>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB5NYUDK5L5GMQH6S6LK57LZXHZ7VAVCNFSM6AAAAABOMT5UKGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJZGQ4DCNJQGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-19 01:12 UTC, axlrommel approved these changes

2024-09-19 01:12 UTC, merged